---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: '>=1.7.0 <2.0.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 12h
  targetNamespace: longhorn-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Minimal resource settings for local development
    defaultSettings:
      defaultReplicaCount: 1
      guaranteedInstanceManagerCPU: 5
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /var/lib/longhorn
      # Optionally set priority class explicitly (already applied by chart defaults)
      priorityClass: longhorn-critical
      # If you prefer automatic disk creation on all nodes without labeling, set createDefaultDiskLabeledNodes: false
      # and remove the node label. Keeping it true requires node label: longhorn.io/create-default-disk=true
      
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      reclaimPolicy: Delete
    
    # Minimal resources for local dev
    longhornManager:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    
    longhornDriver:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
      kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet
    
    longhornUI:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    
    # Disable CSI snapshotter for minimal setup
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
