---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: serviceexample
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: serviceexample
      version: '>=0.2.0'
      sourceRef:
        kind: HelmRepository
        name: serviceexample
        namespace: flux-system
      interval: 5m
  targetNamespace: default
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: serviceexample-values
      valuesKey: values.yaml
